---

- name: Install nginx files and snippets
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0664
  notify: restart nginx
  with_items:
     - { src: nginx.conf.j2, dest: /etc/nginx/nginx.conf }
     - { src: realip-snippet.conf.j2, dest: /etc/nginx/snippets/realip.conf }
     - { src: fpm-snippet.conf.j2, dest: /etc/nginx/snippets/fastcgi-php.conf }
     - { src: x-whom.conf.j2, dest: /etc/nginx/snippets/x-whom.conf }

- name: Enable site config with symlink
  become: yes
  file:
    src: /etc/nginx/sites-available/www.conf
    dest: /etc/nginx/sites-enabled/www.conf
    force: yes
    state: link
  notify: restart nginx

- name: Copy h5bp snippets
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/snippets/"
  with_items:
    - directive-only
    - location
  notify: restart nginx