---

- import_tasks: install.yml
  tags:
    - nginx

- include_tasks: custom.yml
  when: nginx_custom_modules
  tags:
    - nginx-source
    - nginx

- import_tasks: configure.yml
  tags:
    - nginx
    - nginx-configure